#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../test/dummy/config/application',  __FILE__)
ENGINE_PATH = File.expand_path('../../lib/authorizable/engine', __FILE__)
require File.expand_path('../../test/dummy/config/boot',  __FILE__)
require 'rails/commands'
